apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleiades
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pleiades
  template:
    metadata:
      labels:
        app: pleiades
    spec:
      containers:
        - name: pleiades
          image: vardhanyash/pleiades:772559f2663e2c90653bfdcd2b87681b1fc05aa2
          ports:
            - containerPort: 5000