apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleiades
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pleiades
  template:
    metadata:
      labels:
        app: pleiades
    spec:
      containers:
        - name: pleiades
          image: vardhanyash/pleiades:c2834c0fafc3d838b7c041196c4656d41903c6fe
          ports:
            - containerPort: 5000