apiVersion: apps/v1
kind: Deployment
metadata:
  name: pleiades
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pleiades
  template:
    metadata:
      labels:
        app: pleiades
    spec:
      containers:
        - name: pleiades
          image: vardhanyash/pleiades:a1449870145059ea05a5e1da3252db9a05d47450
          ports:
            - containerPort: 5000